# Generated by Django 2.0.7 on 2019-05-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mail', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11)),
            ],
        ),
    ]
